# Zum Aufwärmen

Erstellen Sie **a)** ein NumPy-Array mit folgendem Inhalt:

````python
array([1, 2, 3, 4, 5, 6, 7, 8, 9])
````

In [2]:
import numpy as np

In [4]:
array = np.array([1,2,3,4,5,6,7,8,9])

**b)** Ändern Sie die Gestalt des Arrays in eine 3x6-Matrix, sodass das Ergebnis so aussieht:
    
````python
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])
````
**Hinweis**: Schneiden Sie das Array so zu, dass es für eine 3x6-Gestalt passt.

In [14]:
extended_array = np.arange(1, 19) 
matrix = extended_array.reshape(3, 6)
print(matrix)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


**c)** Zeigen Sie, dass die Shape `(3, 6)` ist.

In [20]:
print(matrix.shape)

(3, 6)


**d)** Berechnen Sie die Summe jeder Spalte. Das Ergebnis sollte ein Array mit sechs Werten sein:

````python
array([21, 24, 27, 30, 33, 36])
````

**Hinweis**: `axis` is your friend!

In [24]:
sum = matrix.sum(axis=0)
print(sum)

[21 24 27 30 33 36]


**e)** Erstellen Sie aus dem ursprünglichen Array ein 3D-Array. Schneiden Sie dafür ggf. Werte weg. Das Ergebnis sollte so aussehen:

````python
array([[[ 1,  2,  3],
        [ 4,  5,  6]],
       
       [[ 7,  8,  9],
        [10, 11, 12]],
       
       [[13, 14, 15],
        [16, 17, 18]]])
````

In [28]:
array_3d = extended_array.reshape(3,2,3)
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
